# Generated by Django 5.2.15 on 2026-08-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_quiz_date_user_quizzes_taken_today_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('features', models.JSONField(default=list)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_quiz_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quizzes_taken_today',
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(default='free', max_length=50),
        ),
    ]
