# Generated by Django 5.2.15 on 2026-08-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscriptionplan_remove_user_last_quiz_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='expiration_date',
        ),
    ]
