# Generated by Django 5.2.15 on 2026-08-07 15:00

from django.db import migrations

def seed_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    
    # Free Plan
    SubscriptionPlan.objects.get_or_create(
        name='free',
        defaults={
            'display_name': 'Free',
            'price': 0,
            'currency': 'NGN',
            'features': ['Access to the first 10 questions of Easy level only'],
            'is_featured': False,
            'is_active': True,
            'order': 0,
        }
    )
    
    # Monthly Plan
    SubscriptionPlan.objects.get_or_create(
        name='monthly',
        defaults={
            'display_name': 'Monthly',
            'price': 1000,
            'currency': 'NGN',
            'features': [
                'Unlimited access to all questions',
                'Detailed step-by-step explanations',
                'Full performance analytics',
                'AI-powered study suggestions',
                'Priority support'
            ],
            'is_featured': True,
            'is_active': True,
            'order': 1,
        }
    )

def reverse_seed(apps, schema_editor):
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(name__in=['free', 'monthly']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260731_1333'),
    ]

    operations = [
        migrations.RunPython(seed_plans, reverse_seed),
    ]
