# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_subscription_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan',
            field=models.CharField(max_length=50),
        ),
    ]
