# Generated by Django 5.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_paymenttransaction_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
