# Generated by Django 5.2.16 on 2026-08-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subscriptionplan_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('tx_ref', models.CharField(blank=True, default='', max_length=100)),
                ('flw_transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('ignored', 'Ignored'), ('error', 'Error')], default='processed', max_length=20)),
                ('discrepancy', models.BooleanField(default=False)),
                ('discrepancy_detail', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
