services:
  backend:
    image: omoluabi44/primary-secondary-backend:latest
    container_name: django_backend
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
