services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    networks:
      - app-network

  backend:
    image: omoluabi44/primary-secondary-backend:latest
    container_name: django_backend
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/gcp-key.json
    ports:
      - "8000:8000"
    volumes:
      - ./gcp-key.json:/app/secrets/gcp-key.json:ro
      - media_volume:/app/media
    depends_on:
      - redis
    networks:
      - app-network

  celery_worker:
    image: omoluabi44/primary-secondary-backend:latest
    container_name: celery_worker
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/gcp-key.json
    volumes:
      - ./gcp-key.json:/app/secrets/gcp-key.json:ro
      - media_volume:/app/media
    depends_on:
      - redis
    command: celery -A config worker --loglevel=info --concurrency=2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  media_volume:
