services:
  frontend:
    image: omoluabi44/primary-secondary-frontend:latest
    container_name: nextjs_frontend
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
