# Generated by Django 5.2.16 on 2026-07-23 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jss_1', 'JSS 1'), ('jss_2', 'JSS 2'), ('jss_3', 'JSS 3'), ('ss_1', 'SS 1'), ('ss_2', 'SS 2'), ('ss_3', 'SS 3')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('exam_body', models.CharField(blank=True, choices=[('federal_common_entrance', 'Federal Common Entrance'), ('state_common_entrance', 'State Common Entrance'), ('bece', 'BECE'), ('waec', 'WAEC'), ('gce', 'GCE'), ('neco', 'NECO'), ('nabteb', 'NABTEB'), ('jamb', 'JAMB')], max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=120, null=True)),
                ('questionText', models.TextField(db_column='questionText')),
                ('questionType', models.CharField(choices=[('mcq', 'MCQ'), ('theory', 'Theory')], db_column='questionType', default='mcq', max_length=10)),
                ('correct_answer', models.CharField(blank=True, max_length=120, null=True)),
                ('incorrect_answers', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('modelAnswer', models.TextField(blank=True, db_column='modelAnswer', null=True)),
                ('markingGuide', models.JSONField(blank=True, db_column='markingGuide', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_questions', to='quiz.subject')),
                ('topic_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_questions', to='quiz.topic')),
            ],
            options={
                'db_table': 'past_questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pastquestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pastquestion'),
        ),
    ]
