# Generated by Django 5.2.15 on 2026-08-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_pastquestion_alter_pastquestionanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='total_questions',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
