# Generated by Django 5.2.15 on 2026-08-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_pastquestion_alter_pastquestionanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='stage_10_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='stage_6_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='stage_7_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='stage_8_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='stage_9_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='total_questions',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
