# Generated by Django 5.2.15 on 2026-08-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_practicesession_stage_10_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastquestion',
            name='image_url',
            field=models.URLField(blank=True, help_text='S3 URL of the question image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='total_questions',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
